# Generated by Django 5.2.9 on 2026-01-14 20:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'db_table': 'accessory',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('siempre_incluir', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'additional_charge',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('DRAFT', 'Draft'), ('CERRADO', 'Cerrado')], default='DRAFT', max_length=10)),
                ('subtotal_maquinas_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_accesorios_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_logistica_hasta_aduana_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_logistica_post_aduana_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('base_pre_impuestos_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_pretax_charges_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('base_imponible_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_impuestos_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_additional_charges_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_aduana_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'db_table': 'budget',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'db_table': 'machine_base',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PreTaxCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('siempre_incluir', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pre_tax_charge',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('siempre_incluir', models.BooleanField(default=False)),
                ('se_imprime_en_presupuesto', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tax',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAdditionalChargeApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incluido', models.BooleanField(default=True)),
                ('porcentaje_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('monto_minimo_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_aplicado_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('additional_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_additional_charges', to='machinery.additionalcharge')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='machinery.budget')),
            ],
            options={
                'db_table': 'budget_additional_charge_applied',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('machine_total_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_maquina_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='machinery.budget')),
                ('machine_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='machinery.machinebase')),
            ],
            options={
                'db_table': 'budget_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='client_nombre_596db9_idx')],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='machinery.client'),
        ),
        migrations.CreateModel(
            name='LogisticsLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desde', models.CharField(max_length=200)),
                ('hasta', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('AEREO', 'Aéreo'), ('MARITIMO', 'Marítimo')], max_length=20)),
                ('etapa', models.CharField(choices=[('HASTA_ADUANA', 'Hasta aduana'), ('POST_ADUANA', 'Post aduana')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'db_table': 'logistics_leg',
                'ordering': ['etapa', 'desde', 'hasta', 'tipo'],
                'indexes': [models.Index(fields=['etapa'], name='logistics_l_etapa_610d38_idx'), models.Index(fields=['tipo'], name='logistics_l_tipo_4a3e9a_idx')],
                'constraints': [models.UniqueConstraint(fields=('desde', 'hasta', 'tipo', 'etapa'), name='uq_logistics_leg_route')],
            },
        ),
        migrations.CreateModel(
            name='BudgetSelectedLogisticsLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logisticas', to='machinery.budget')),
                ('logistics_leg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_selections', to='machinery.logisticsleg')),
            ],
            options={
                'db_table': 'budget_selected_logistics_leg',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPreTaxChargeApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incluido', models.BooleanField(default=True)),
                ('porcentaje_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('monto_aplicado_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretax_charges', to='machinery.budget')),
                ('pre_tax_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_pretax_charges', to='machinery.pretaxcharge')),
            ],
            options={
                'db_table': 'budget_pre_tax_charge_applied',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_compra', models.DateField()),
                ('total_snapshot', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notas', models.TextField(blank=True, default='')),
                ('budget', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='machinery.budget')),
            ],
            options={
                'db_table': 'purchase',
                'ordering': ['-fecha_compra', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('ALQUILADA', 'Alquilada'), ('VENDIDA', 'Vendida')], default='DEPOSITO', max_length=12)),
                ('identificador', models.CharField(blank=True, default='', max_length=200)),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_compradas', to='machinery.budgetitem')),
                ('machine_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_compradas', to='machinery.machinebase')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='machinery.purchase')),
            ],
            options={
                'db_table': 'purchased_unit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('ALQUILER', 'Alquiler')], max_length=10)),
                ('fecha_operacion', models.DateField(blank=True, null=True)),
                ('rental_tipo', models.CharField(blank=True, choices=[('MENSUAL', 'Mensual'), ('SEMANAL', 'Semanal'), ('DIARIO', 'Diario')], max_length=10, null=True)),
                ('rental_inicio', models.DateField(blank=True, null=True)),
                ('rental_fin_estimado', models.DateField(blank=True, null=True)),
                ('rental_fin_real', models.DateField(blank=True, null=True)),
                ('monto_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_total_final', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notas', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_events', to='machinery.client')),
            ],
            options={
                'db_table': 'revenue_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueEventUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_usos', to='machinery.purchasedunit')),
                ('revenue_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='machinery.revenueevent')),
            ],
            options={
                'db_table': 'revenue_event_unit',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RevenuePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('TARJETA_CREDITO', 'Tarjeta crédito'), ('CHEQUE', 'Cheque')], max_length=30)),
                ('fecha_prevista', models.DateField()),
                ('cobrado', models.BooleanField(default=False)),
                ('fecha_cobro_real', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('revenue_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='machinery.revenueevent')),
            ],
            options={
                'db_table': 'revenue_payment',
                'ordering': ['fecha_prevista', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTaxApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incluido', models.BooleanField(default=True)),
                ('porcentaje_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('monto_minimo_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_aplicado_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='machinery.budget')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_taxes', to='machinery.tax')),
            ],
            options={
                'db_table': 'budget_tax_applied',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItemAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('accessory_total_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_item_accessories', to='machinery.accessory')),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorios', to='machinery.budgetitem')),
            ],
            options={
                'db_table': 'budget_item_accessory',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['budget_item'], name='budget_item_budget__6f4748_idx'), models.Index(fields=['accessory'], name='budget_item_accesso_df6df0_idx')],
                'constraints': [models.UniqueConstraint(fields=('budget_item', 'accessory'), name='uq_budget_item_accessory')],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['estado'], name='budget_estado_7968b9_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['fecha'], name='budget_fecha_4d1177_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetselectedlogisticsleg',
            index=models.Index(fields=['budget'], name='budget_sele_budget__744e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetselectedlogisticsleg',
            index=models.Index(fields=['logistics_leg'], name='budget_sele_logisti_80a21e_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetselectedlogisticsleg',
            constraint=models.UniqueConstraint(fields=('budget', 'logistics_leg'), name='uq_budget_selected_logistics_leg'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['budget'], name='budget_item_budget__cef243_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['machine_base'], name='budget_item_machine_b66a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetpretaxchargeapplied',
            index=models.Index(fields=['budget'], name='budget_pre__budget__7de801_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetpretaxchargeapplied',
            index=models.Index(fields=['pre_tax_charge'], name='budget_pre__pre_tax_2c213f_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetpretaxchargeapplied',
            constraint=models.UniqueConstraint(fields=('budget', 'pre_tax_charge'), name='uq_budget_pretax_charge'),
        ),
        migrations.AddIndex(
            model_name='purchasedunit',
            index=models.Index(fields=['estado'], name='purchased_u_estado_3b25fa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedunit',
            index=models.Index(fields=['machine_base'], name='purchased_u_machine_694c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedunit',
            index=models.Index(fields=['purchase'], name='purchased_u_purchas_3780c0_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueevent',
            index=models.Index(fields=['tipo'], name='revenue_eve_tipo_4fa947_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueevent',
            index=models.Index(fields=['fecha_operacion'], name='revenue_eve_fecha_o_1d3fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueevent',
            index=models.Index(fields=['cliente'], name='revenue_eve_cliente_f99500_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenueevent',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'ALQUILER'), models.Q(('tipo', 'VENTA'), ('fecha_operacion__isnull', False), ('rental_tipo__isnull', True), ('rental_inicio__isnull', True), ('rental_fin_estimado__isnull', True), ('rental_fin_real__isnull', True), ('monto_unitario__isnull', True)), _connector='OR'), name='ck_revenue_event_sale_fields'),
        ),
        migrations.AddConstraint(
            model_name='revenueevent',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'VENTA'), models.Q(('tipo', 'ALQUILER'), ('rental_tipo__isnull', False), ('rental_inicio__isnull', False), ('rental_fin_estimado__isnull', False), ('monto_unitario__isnull', False)), _connector='OR'), name='ck_revenue_event_rental_requires_fields'),
        ),
        migrations.AddConstraint(
            model_name='revenueevent',
            constraint=models.CheckConstraint(condition=models.Q(('rental_fin_real__isnull', True), ('rental_fin_real__gte', models.F('rental_inicio')), _connector='OR'), name='ck_revenue_rental_fin_real_gte_inicio'),
        ),
        migrations.AddIndex(
            model_name='revenueeventunit',
            index=models.Index(fields=['revenue_event'], name='revenue_eve_revenue_76b123_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueeventunit',
            index=models.Index(fields=['purchased_unit'], name='revenue_eve_purchas_cf3c67_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenueeventunit',
            constraint=models.UniqueConstraint(fields=('revenue_event', 'purchased_unit'), name='uq_revenue_event_unit'),
        ),
        migrations.AddIndex(
            model_name='revenuepayment',
            index=models.Index(fields=['fecha_prevista'], name='revenue_pay_fecha_p_3b6fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuepayment',
            index=models.Index(fields=['cobrado'], name='revenue_pay_cobrado_c0d5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuepayment',
            index=models.Index(fields=['fecha_cobro_real'], name='revenue_pay_fecha_c_516319_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuepayment',
            index=models.Index(fields=['metodo_pago'], name='revenue_pay_metodo__bfaf03_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuepayment',
            index=models.Index(fields=['revenue_event'], name='revenue_pay_revenue_41911e_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenuepayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cobrado', False), ('fecha_cobro_real__isnull', True)), models.Q(('cobrado', True), ('fecha_cobro_real__isnull', False)), _connector='OR'), name='ck_revenue_payment_cobrado_fecha_real_consistency'),
        ),
        migrations.AddIndex(
            model_name='budgettaxapplied',
            index=models.Index(fields=['budget'], name='budget_tax__budget__9f9262_idx'),
        ),
        migrations.AddIndex(
            model_name='budgettaxapplied',
            index=models.Index(fields=['tax'], name='budget_tax__tax_id_560683_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgettaxapplied',
            constraint=models.UniqueConstraint(fields=('budget', 'tax'), name='uq_budget_tax'),
        ),
    ]
