# Generated by Django 5.2.9 on 2026-01-14 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='machinery.budget'),
        ),
        migrations.AlterField(
            model_name='revenueeventunit',
            name='purchased_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_usos', to='machinery.purchasedunit'),
        ),
    ]
